language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
dist: trusty

addons:
  sonarcloud:
    organization: "jhawk1196"
    token:
      secure: SONAR-TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  - python tests.py